import { createSignal, For } from "solid-js";
import { createQuery } from "@tanstack/solid-query";
import { fetchCurrentAccount } from "../api/client";
import { Avatar, Badge, Button, Checkbox, ContextMenu, Dialog, Icon, Radio, Select, Switch, TextField, Toast, Tooltip } from "../components/ui";
import { getLocale, setLocale, t, type AppLocale } from "../i18n";
export function Foundation() {
  const account = createQuery(() => ({ queryKey: ["auth", "me"], queryFn: fetchCurrentAccount, retry: false }));
  const [theme, setTheme] = createSignal<"dark"|"light">("dark"); const [open,setOpen]=createSignal(false); const [toast,setToast]=createSignal(false); const [locale,setLocaleView]=createSignal<AppLocale>(getLocale());
  const toggleTheme=(value:"dark"|"light")=>{setTheme(value);document.documentElement.dataset.theme=value;};
  const changeLocale=(value:AppLocale)=>{setLocale(value);setLocaleView(value);};
  const notify=()=>{setToast(true);window.setTimeout(()=>setToast(false),2400);};
  return <main class="foundation"><header class="foundation-head"><div><Badge tone="secure">Campfire Modernism</Badge><h1>{t("foundation.title")}</h1><p>{t("foundation.description")}</p></div><div class="toolbar"><label>{t("foundation.theme")}<select value={theme()} onChange={(e)=>toggleTheme(e.currentTarget.value as "dark"|"light")}><option value="dark">{t("foundation.dark")}</option><option value="light">{t("foundation.light")}</option></select></label><label>{t("foundation.language")}<select value={locale()} onChange={(e)=>changeLocale(e.currentTarget.value as AppLocale)}><option value="pt-BR">pt-BR</option><option value="en">English</option></select></label></div></header>
    <section class="demo-card"><h2>{t("foundation.buttons")}</h2><div class="demo-row"><Button variant="primary" onClick={notify}><Icon name="check"/>Primary</Button><Button variant="secondary">Secondary</Button><Button variant="danger">Danger</Button><Button variant="icon" title="Search"><Icon name="search"/></Button><Button variant="icon" title="Settings"><Icon name="settings"/></Button><Icon name="mic"/></div></section>
    <section class="demo-card"><h2>{t("foundation.forms")}</h2><div class="demo-grid"><TextField label={t("foundation.input")} placeholder={t("foundation.sample")}/><TextField label={t("foundation.required")} error={t("foundation.error")} value="bad value"/><TextField label={t("foundation.disabled")} disabled value="Disabled"/><fieldset><legend>{t("foundation.radio")}</legend><Radio name="sample" value="one" checked>One</Radio><Radio name="sample" value="two" disabled>Disabled</Radio><Radio name="error" value="error" error={t("foundation.error")}>Error</Radio></fieldset><Checkbox checked>{t("foundation.checkbox")}</Checkbox><Checkbox disabled>{t("foundation.disabled")}</Checkbox><Checkbox error={t("foundation.error")}>Error</Checkbox><Switch label={t("foundation.switch")} checked/><Switch label={t("foundation.disabled")} disabled/><Switch label="Error" error={t("foundation.error")}/><Select label={t("foundation.select")}><option>Option one</option><option>Option two</option></Select><Select label="Disabled" disabled><option>Disabled</option></Select><Select label="Error" error={t("foundation.error")}><option>Invalid value</option></Select></div></section>
    <section class="demo-card"><h2>{t("foundation.components")}</h2><div class="demo-row"><Button onClick={()=>setOpen(true)}>{t("foundation.openDialog")}</Button><Button onClick={notify}>{t("foundation.toast")}</Button><ContextMenu items={[{label:"Edit",action:notify},{label:"Delete",danger:true,action:notify}]}><Button variant="secondary">{t("foundation.context")}</Button></ContextMenu><Avatar name="Mesa" online/><Avatar name="Offline"/><Badge>Primary</Badge><Badge tone="secure">{t("foundation.badge")}</Badge><Badge tone="danger">Danger</Badge><Tooltip text={t("foundation.tooltip")}><Button variant="icon"><Icon name="help"/></Button></Tooltip><For each={["lock","mic","search","settings","person"]}>{name=><Icon name={name}/>}</For></div></section>
    <section class="demo-card"><h2>QueryClient · GET /api/auth/me</h2><p>Loading: {String(account.isPending)} · Error: {String(account.isError)} · Success: {String(account.isSuccess)}</p></section>
    <section class="demo-card token-preview"><h2>Tokens · {theme()}</h2><div class="swatches">{["background","surface-container-low","surface-container","surface-container-high","primary-container","secondary","tertiary","error"].map(name=><div><span style={{background:`var(--${name})`}}/><code>{name}</code></div>)}<div><span class="bg-red-500"/><code>Tailwind bg-red-500</code></div><div><span class="bg-primary-container"/><code>bg-primary-container</code></div></div><div class="breakpoints"><span class="mobile-only">Mobile &lt;768</span><span class="tablet-only">Tablet 768–1024</span><span class="desktop-only">Desktop 1025+</span></div></section>
    <Dialog open={open()} title={t("foundation.dialog")} onClose={()=>setOpen(false)}><p>{t("foundation.dialogBody")}</p><Button variant="primary" onClick={()=>setOpen(false)}>{t("foundation.close")}</Button></Dialog><Toast message={t("foundation.notify")} show={toast()}/>
  </main>;
}
