[package]
name = "mesa"
version = "1.2.0"
description = "Mesa desktop shell"
authors = []
license = "AGPL-3.0-only"
repository = ""
edition = "2024"
rust-version = "1.90"

[lib]
name = "mesa_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.7.1", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.12.1", features = [] }
tauri-plugin-log = "2"
tauri-plugin-http = "2"
tauri-plugin-store = "2"
tauri-plugin-websocket = "2"

[target.'cfg(target_os = "linux")'.dependencies]
webkit2gtk = "2.0.2"
