export type EmojiEntry = {
  shortcode: string;
  glyph: string;
  keywords?: string[];
};

/** Useful Unicode emoji shortcode catalog (gemoji-style names). */
export const EMOJI_CATALOG: EmojiEntry[] = [
  { shortcode: "smile", glyph: "😄", keywords: ["happy", "face"] },
  { shortcode: "smiley", glyph: "😃", keywords: ["happy"] },
  { shortcode: "grinning", glyph: "😀", keywords: ["happy"] },
  { shortcode: "grin", glyph: "😁", keywords: ["happy"] },
  { shortcode: "laughing", glyph: "😆", keywords: ["lol", "happy"] },
  { shortcode: "sweat_smile", glyph: "😅", keywords: ["relief"] },
  { shortcode: "joy", glyph: "😂", keywords: ["tears", "lol"] },
  { shortcode: "rofl", glyph: "🤣", keywords: ["lol"] },
  { shortcode: "relaxed", glyph: "☺️", keywords: ["smile"] },
  { shortcode: "blush", glyph: "😊", keywords: ["shy"] },
  { shortcode: "innocent", glyph: "😇", keywords: ["angel"] },
  { shortcode: "slightly_smiling_face", glyph: "🙂", keywords: ["smile"] },
  { shortcode: "upside_down_face", glyph: "🙃", keywords: ["silly"] },
  { shortcode: "wink", glyph: "😉", keywords: ["flirt"] },
  { shortcode: "relieved", glyph: "😌", keywords: ["calm"] },
  { shortcode: "heart_eyes", glyph: "😍", keywords: ["love"] },
  { shortcode: "smiling_face_with_three_hearts", glyph: "🥰", keywords: ["love"] },
  { shortcode: "kissing_heart", glyph: "😘", keywords: ["kiss"] },
  { shortcode: "kissing", glyph: "😗", keywords: ["kiss"] },
  { shortcode: "yum", glyph: "😋", keywords: ["food"] },
  { shortcode: "stuck_out_tongue", glyph: "😛", keywords: ["tongue"] },
  { shortcode: "stuck_out_tongue_winking_eye", glyph: "😜", keywords: ["silly"] },
  { shortcode: "zany_face", glyph: "🤪", keywords: ["crazy"] },
  { shortcode: "raised_eyebrow", glyph: "🤨", keywords: ["skeptical"] },
  { shortcode: "monocle_face", glyph: "🧐", keywords: ["think"] },
  { shortcode: "nerd_face", glyph: "🤓", keywords: ["geek"] },
  { shortcode: "sunglasses", glyph: "😎", keywords: ["cool"] },
  { shortcode: "star_struck", glyph: "🤩", keywords: ["stars"] },
  { shortcode: "partying_face", glyph: "🥳", keywords: ["party"] },
  { shortcode: "smirk", glyph: "😏", keywords: ["smug"] },
  { shortcode: "unamused", glyph: "😒", keywords: ["meh"] },
  { shortcode: "disappointed", glyph: "😞", keywords: ["sad"] },
  { shortcode: "pensive", glyph: "😔", keywords: ["sad"] },
  { shortcode: "worried", glyph: "😟", keywords: ["anxiety"] },
  { shortcode: "confused", glyph: "😕", keywords: ["huh"] },
  { shortcode: "slightly_frowning_face", glyph: "🙁", keywords: ["sad"] },
  { shortcode: "frowning_face", glyph: "☹️", keywords: ["sad"] },
  { shortcode: "persevere", glyph: "😣", keywords: ["struggle"] },
  { shortcode: "confounded", glyph: "😖", keywords: ["upset"] },
  { shortcode: "tired_face", glyph: "😫", keywords: ["tired"] },
  { shortcode: "weary", glyph: "😩", keywords: ["tired"] },
  { shortcode: "pleading_face", glyph: "🥺", keywords: ["please"] },
  { shortcode: "cry", glyph: "😢", keywords: ["tear", "sad"] },
  { shortcode: "sob", glyph: "😭", keywords: ["cry"] },
  { shortcode: "triumph", glyph: "😤", keywords: ["huff"] },
  { shortcode: "angry", glyph: "😠", keywords: ["mad"] },
  { shortcode: "rage", glyph: "😡", keywords: ["mad"] },
  { shortcode: "exploding_head", glyph: "🤯", keywords: ["mindblown"] },
  { shortcode: "flushed", glyph: "😳", keywords: ["embarrassed"] },
  { shortcode: "hot_face", glyph: "🥵", keywords: ["hot"] },
  { shortcode: "cold_face", glyph: "🥶", keywords: ["cold"] },
  { shortcode: "scream", glyph: "😱", keywords: ["fear"] },
  { shortcode: "fearful", glyph: "😨", keywords: ["fear"] },
  { shortcode: "thinking", glyph: "🤔", keywords: ["hmm"] },
  { shortcode: "shushing_face", glyph: "🤫", keywords: ["quiet"] },
  { shortcode: "lying_face", glyph: "🤥", keywords: ["lie"] },
  { shortcode: "neutral_face", glyph: "😐", keywords: ["blank"] },
  { shortcode: "expressionless", glyph: "😑", keywords: ["blank"] },
  { shortcode: "no_mouth", glyph: "😶", keywords: ["silent"] },
  { shortcode: "roll_eyes", glyph: "🙄", keywords: ["eyeroll"] },
  { shortcode: "hugs", glyph: "🤗", keywords: ["hug"] },
  { shortcode: "face_with_hand_over_mouth", glyph: "🤭", keywords: ["oops"] },
  { shortcode: "yawning_face", glyph: "🥱", keywords: ["tired"] },
  { shortcode: "sleeping", glyph: "😴", keywords: ["sleep"] },
  { shortcode: "drooling_face", glyph: "🤤", keywords: ["hungry"] },
  { shortcode: "dizzy_face", glyph: "😵", keywords: ["dizzy"] },
  { shortcode: "zipper_mouth_face", glyph: "🤐", keywords: ["secret"] },
  { shortcode: "woozy_face", glyph: "🥴", keywords: ["drunk"] },
  { shortcode: "nauseated_face", glyph: "🤢", keywords: ["sick"] },
  { shortcode: "sneezing_face", glyph: "🤧", keywords: ["sick"] },
  { shortcode: "mask", glyph: "😷", keywords: ["sick"] },
  { shortcode: "face_with_thermometer", glyph: "🤒", keywords: ["sick"] },
  { shortcode: "face_with_head_bandage", glyph: "🤕", keywords: ["hurt"] },
  { shortcode: "money_mouth_face", glyph: "🤑", keywords: ["money"] },
  { shortcode: "cowboy_hat_face", glyph: "🤠", keywords: ["cowboy"] },
  { shortcode: "smiling_imp", glyph: "😈", keywords: ["devil"] },
  { shortcode: "imp", glyph: "👿", keywords: ["devil"] },
  { shortcode: "ghost", glyph: "👻", keywords: ["halloween"] },
  { shortcode: "skull", glyph: "💀", keywords: ["dead"] },
  { shortcode: "robot", glyph: "🤖", keywords: ["bot"] },
  { shortcode: "cat", glyph: "🐱", keywords: ["animal"] },
  { shortcode: "dog", glyph: "🐶", keywords: ["animal"] },
  { shortcode: "fox_face", glyph: "🦊", keywords: ["animal"] },
  { shortcode: "lion", glyph: "🦁", keywords: ["animal"] },
  { shortcode: "fire", glyph: "🔥", keywords: ["hot", "lit"] },
  { shortcode: "sparkles", glyph: "✨", keywords: ["magic"] },
  { shortcode: "star", glyph: "⭐", keywords: ["favorite"] },
  { shortcode: "boom", glyph: "💥", keywords: ["explosion"] },
  { shortcode: "100", glyph: "💯", keywords: ["perfect"] },
  { shortcode: "heart", glyph: "❤️", keywords: ["love"] },
  { shortcode: "orange_heart", glyph: "🧡", keywords: ["love"] },
  { shortcode: "yellow_heart", glyph: "💛", keywords: ["love"] },
  { shortcode: "green_heart", glyph: "💚", keywords: ["love"] },
  { shortcode: "blue_heart", glyph: "💙", keywords: ["love"] },
  { shortcode: "purple_heart", glyph: "💜", keywords: ["love"] },
  { shortcode: "black_heart", glyph: "🖤", keywords: ["love"] },
  { shortcode: "white_heart", glyph: "🤍", keywords: ["love"] },
  { shortcode: "broken_heart", glyph: "💔", keywords: ["sad"] },
  { shortcode: "two_hearts", glyph: "💕", keywords: ["love"] },
  { shortcode: "revolving_hearts", glyph: "💞", keywords: ["love"] },
  { shortcode: "heartbeat", glyph: "💓", keywords: ["love"] },
  { shortcode: "heartpulse", glyph: "💗", keywords: ["love"] },
  { shortcode: "sparkling_heart", glyph: "💖", keywords: ["love"] },
  { shortcode: "cupid", glyph: "💘", keywords: ["love"] },
  { shortcode: "gift_heart", glyph: "💝", keywords: ["love"] },
  { shortcode: "thumbsup", glyph: "👍", keywords: ["ok", "+1", "yes"] },
  { shortcode: "+1", glyph: "👍", keywords: ["thumbsup"] },
  { shortcode: "thumbsdown", glyph: "👎", keywords: ["no", "-1"] },
  { shortcode: "-1", glyph: "👎", keywords: ["thumbsdown"] },
  { shortcode: "ok_hand", glyph: "👌", keywords: ["ok"] },
  { shortcode: "clap", glyph: "👏", keywords: ["applause"] },
  { shortcode: "raised_hands", glyph: "🙌", keywords: ["celebrate"] },
  { shortcode: "open_hands", glyph: "👐", keywords: ["hands"] },
  { shortcode: "palms_up_together", glyph: "🤲", keywords: ["pray"] },
  { shortcode: "handshake", glyph: "🤝", keywords: ["deal"] },
  { shortcode: "pray", glyph: "🙏", keywords: ["thanks", "please"] },
  { shortcode: "writing_hand", glyph: "✍️", keywords: ["write"] },
  { shortcode: "nail_care", glyph: "💅", keywords: ["nails"] },
  { shortcode: "selfie", glyph: "🤳", keywords: ["photo"] },
  { shortcode: "muscle", glyph: "💪", keywords: ["strong"] },
  { shortcode: "leg", glyph: "🦵", keywords: ["kick"] },
  { shortcode: "foot", glyph: "🦶", keywords: ["kick"] },
  { shortcode: "ear", glyph: "👂", keywords: ["listen"] },
  { shortcode: "nose", glyph: "👃", keywords: ["smell"] },
  { shortcode: "brain", glyph: "🧠", keywords: ["smart"] },
  { shortcode: "eyes", glyph: "👀", keywords: ["look"] },
  { shortcode: "eye", glyph: "👁️", keywords: ["look"] },
  { shortcode: "tongue", glyph: "👅", keywords: ["taste"] },
  { shortcode: "lips", glyph: "👄", keywords: ["kiss"] },
  { shortcode: "baby", glyph: "👶", keywords: ["child"] },
  { shortcode: "child", glyph: "🧒", keywords: ["kid"] },
  { shortcode: "boy", glyph: "👦", keywords: ["kid"] },
  { shortcode: "girl", glyph: "👧", keywords: ["kid"] },
  { shortcode: "adult", glyph: "🧑", keywords: ["person"] },
  { shortcode: "man", glyph: "👨", keywords: ["person"] },
  { shortcode: "woman", glyph: "👩", keywords: ["person"] },
  { shortcode: "wave", glyph: "👋", keywords: ["hi", "hello", "bye"] },
  { shortcode: "raised_hand", glyph: "✋", keywords: ["stop"] },
  { shortcode: "vulcan_salute", glyph: "🖖", keywords: ["spock"] },
  { shortcode: "pinching_hand", glyph: "🤏", keywords: ["small"] },
  { shortcode: "v", glyph: "✌️", keywords: ["peace"] },
  { shortcode: "crossed_fingers", glyph: "🤞", keywords: ["luck"] },
  { shortcode: "love_you_gesture", glyph: "🤟", keywords: ["love"] },
  { shortcode: "metal", glyph: "🤘", keywords: ["rock"] },
  { shortcode: "call_me_hand", glyph: "🤙", keywords: ["call"] },
  { shortcode: "point_left", glyph: "👈", keywords: ["left"] },
  { shortcode: "point_right", glyph: "👉", keywords: ["right"] },
  { shortcode: "point_up_2", glyph: "👆", keywords: ["up"] },
  { shortcode: "point_down", glyph: "👇", keywords: ["down"] },
  { shortcode: "point_up", glyph: "☝️", keywords: ["up"] },
  { shortcode: "middle_finger", glyph: "🖕", keywords: ["rude"] },
  { shortcode: "fist", glyph: "✊", keywords: ["power"] },
  { shortcode: "facepunch", glyph: "👊", keywords: ["punch"] },
  { shortcode: "left_facing_fist", glyph: "🤛", keywords: ["punch"] },
  { shortcode: "right_facing_fist", glyph: "🤜", keywords: ["punch"] },
  { shortcode: "tada", glyph: "🎉", keywords: ["party", "celebrate"] },
  { shortcode: "confetti_ball", glyph: "🎊", keywords: ["party"] },
  { shortcode: "balloon", glyph: "🎈", keywords: ["party"] },
  { shortcode: "gift", glyph: "🎁", keywords: ["present"] },
  { shortcode: "trophy", glyph: "🏆", keywords: ["win"] },
  { shortcode: "medal_sports", glyph: "🏅", keywords: ["win"] },
  { shortcode: "soccer", glyph: "⚽", keywords: ["football"] },
  { shortcode: "basketball", glyph: "🏀", keywords: ["sport"] },
  { shortcode: "coffee", glyph: "☕", keywords: ["drink"] },
  { shortcode: "tea", glyph: "🍵", keywords: ["drink"] },
  { shortcode: "beer", glyph: "🍺", keywords: ["drink"] },
  { shortcode: "beers", glyph: "🍻", keywords: ["drink"] },
  { shortcode: "wine_glass", glyph: "🍷", keywords: ["drink"] },
  { shortcode: "pizza", glyph: "🍕", keywords: ["food"] },
  { shortcode: "hamburger", glyph: "🍔", keywords: ["food"] },
  { shortcode: "fries", glyph: "🍟", keywords: ["food"] },
  { shortcode: "cake", glyph: "🍰", keywords: ["dessert"] },
  { shortcode: "cookie", glyph: "🍪", keywords: ["food"] },
  { shortcode: "apple", glyph: "🍎", keywords: ["fruit"] },
  { shortcode: "banana", glyph: "🍌", keywords: ["fruit"] },
  { shortcode: "rocket", glyph: "🚀", keywords: ["launch"] },
  { shortcode: "airplane", glyph: "✈️", keywords: ["travel"] },
  { shortcode: "car", glyph: "🚗", keywords: ["drive"] },
  { shortcode: "bike", glyph: "🚲", keywords: ["cycle"] },
  { shortcode: "house", glyph: "🏠", keywords: ["home"] },
  { shortcode: "office", glyph: "🏢", keywords: ["work"] },
  { shortcode: "computer", glyph: "💻", keywords: ["laptop"] },
  { shortcode: "iphone", glyph: "📱", keywords: ["phone"] },
  { shortcode: "email", glyph: "📧", keywords: ["mail"] },
  { shortcode: "memo", glyph: "📝", keywords: ["note"] },
  { shortcode: "books", glyph: "📚", keywords: ["read"] },
  { shortcode: "bulb", glyph: "💡", keywords: ["idea"] },
  { shortcode: "lock", glyph: "🔒", keywords: ["secure"] },
  { shortcode: "unlock", glyph: "🔓", keywords: ["open"] },
  { shortcode: "key", glyph: "🔑", keywords: ["access"] },
  { shortcode: "hammer", glyph: "🔨", keywords: ["build"] },
  { shortcode: "wrench", glyph: "🔧", keywords: ["fix"] },
  { shortcode: "gear", glyph: "⚙️", keywords: ["settings"] },
  { shortcode: "warning", glyph: "⚠️", keywords: ["caution"] },
  { shortcode: "no_entry", glyph: "⛔", keywords: ["stop"] },
  { shortcode: "white_check_mark", glyph: "✅", keywords: ["done", "ok"] },
  { shortcode: "x", glyph: "❌", keywords: ["no", "wrong"] },
  { shortcode: "question", glyph: "❓", keywords: ["help"] },
  { shortcode: "exclamation", glyph: "❗", keywords: ["bang"] },
  { shortcode: "zzz", glyph: "💤", keywords: ["sleep"] },
  { shortcode: "dash", glyph: "💨", keywords: ["fast"] },
  { shortcode: "sweat_drops", glyph: "💦", keywords: ["water"] },
  { shortcode: "dizzy", glyph: "💫", keywords: ["star"] },
  { shortcode: "speech_balloon", glyph: "💬", keywords: ["chat"] },
  { shortcode: "thought_balloon", glyph: "💭", keywords: ["think"] },
  { shortcode: "bell", glyph: "🔔", keywords: ["notify"] },
  { shortcode: "no_bell", glyph: "🔕", keywords: ["mute"] },
  { shortcode: "mega", glyph: "📣", keywords: ["announce"] },
  { shortcode: "loudspeaker", glyph: "📢", keywords: ["announce"] },
  { shortcode: "musical_note", glyph: "🎵", keywords: ["music"] },
  { shortcode: "notes", glyph: "🎶", keywords: ["music"] },
  { shortcode: "headphones", glyph: "🎧", keywords: ["music"] },
  { shortcode: "camera", glyph: "📷", keywords: ["photo"] },
  { shortcode: "movie_camera", glyph: "🎥", keywords: ["video"] },
  { shortcode: "tv", glyph: "📺", keywords: ["watch"] },
  { shortcode: "hourglass", glyph: "⌛", keywords: ["time"] },
  { shortcode: "alarm_clock", glyph: "⏰", keywords: ["time"] },
  { shortcode: "watch", glyph: "⌚", keywords: ["time"] },
  { shortcode: "sunny", glyph: "☀️", keywords: ["weather"] },
  { shortcode: "cloud", glyph: "☁️", keywords: ["weather"] },
  { shortcode: "rain_cloud", glyph: "🌧️", keywords: ["weather"] },
  { shortcode: "snowflake", glyph: "❄️", keywords: ["cold"] },
  { shortcode: "zap", glyph: "⚡", keywords: ["lightning"] },
  { shortcode: "umbrella", glyph: "☂️", keywords: ["rain"] },
  { shortcode: "rainbow", glyph: "🌈", keywords: ["pride"] },
  { shortcode: "ocean", glyph: "🌊", keywords: ["water"] },
  { shortcode: "earth_americas", glyph: "🌎", keywords: ["world"] },
  { shortcode: "moon", glyph: "🌙", keywords: ["night"] },
  { shortcode: "sun_with_face", glyph: "🌞", keywords: ["day"] },
  { shortcode: "new_moon_with_face", glyph: "🌚", keywords: ["night"] },
  { shortcode: "full_moon_with_face", glyph: "🌝", keywords: ["night"] },
  { shortcode: "checkered_flag", glyph: "🏁", keywords: ["finish"] },
  { shortcode: "triangular_flag_on_post", glyph: "🚩", keywords: ["flag"] },
  { shortcode: "see_no_evil", glyph: "🙈", keywords: ["monkey"] },
  { shortcode: "hear_no_evil", glyph: "🙉", keywords: ["monkey"] },
  { shortcode: "speak_no_evil", glyph: "🙊", keywords: ["monkey"] },
  { shortcode: "monkey_face", glyph: "🐵", keywords: ["animal"] },
  { shortcode: "penguin", glyph: "🐧", keywords: ["animal"] },
  { shortcode: "bird", glyph: "🐦", keywords: ["animal"] },
  { shortcode: "snake", glyph: "🐍", keywords: ["animal"] },
  { shortcode: "dragon", glyph: "🐉", keywords: ["fantasy"] },
  { shortcode: "unicorn", glyph: "🦄", keywords: ["fantasy"] },
  { shortcode: "bee", glyph: "🐝", keywords: ["insect"] },
  { shortcode: "bug", glyph: "🐛", keywords: ["insect"] },
  { shortcode: "cherry_blossom", glyph: "🌸", keywords: ["flower"] },
  { shortcode: "rose", glyph: "🌹", keywords: ["flower"] },
  { shortcode: "sunflower", glyph: "🌻", keywords: ["flower"] },
  { shortcode: "herb", glyph: "🌿", keywords: ["plant"] },
  { shortcode: "four_leaf_clover", glyph: "🍀", keywords: ["luck"] },
  { shortcode: "maple_leaf", glyph: "🍁", keywords: ["fall"] },
  { shortcode: "fallen_leaf", glyph: "🍂", keywords: ["fall"] },
  { shortcode: "leaves", glyph: "🍃", keywords: ["wind"] },
];

/** Deduped catalog (first shortcode wins for duplicate glyphs). */
export function uniqueEmojiCatalog(): EmojiEntry[] {
  const seen = new Set<string>();
  const out: EmojiEntry[] = [];
  for (const e of EMOJI_CATALOG) {
    const key = e.shortcode.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(e);
  }
  return out;
}
